version: '3.8'

services:
  api:
    image: node:20.10.0-alpine
    container_name: talimpo-api
    working_dir: /app
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./:/app
    command: yarn start:dev
    ports:
      - "3000:3000"

  postgres:
    image: postgres:16-alpine
    container_name: talimpo-postgres
    environment:
      POSTGRES_USER: talimpo_user
      POSTGRES_PASSWORD: talimpo_password
      POSTGRES_DB: talimpo_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
